# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"  # Specificeer dat je GitHub Actions wilt monitoren
    directory: "/"  # De directory waarin je .yml-bestanden zich bevinden
    schedule:
      interval: "weekly"  # Controleer wekelijks op updates
