version: "3.8" # als je versie gebruikt, zorg ervoor dat deze de juiste versie is

services:
  webapp:
    build: jonas12janssens/webapp
    ports:
      - "3000:3000"
    environment:
      MYSQL_URL: mysql://user:user_password@database:3306/animals
    depends_on:
      - database
    restart: on-failure

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: animals
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  tests:
    image: jonas12janssens/webapp # Hergebruik de bestaande image van webapp
    environment:
      API_URL: http://webapp:3000 # Gebruik de service naam als hostname
    depends_on:
      - webapp
    command: yarn test # Voer de Mocha tests uit
volumes:
  mysql_data:
