name: Build, test, and push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Check de repository-code uit
      - name: Check out repository code
        uses: actions/checkout@v3

      # Stap 2: Installeer NodeJS
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Stap 3: Installeer dependencies
      - name: Installeer dependencies
        run: |
          cd webapp
          yarn install

      # Stap 4: Start de server in de achtergrond
      - name: Start the server
        run: |
          cd webapp
          nohup yarn start &

      # Stap 5: Wacht tot de server beschikbaar is
      - name: Wait for server to be ready
        run: sleep 5

      # Stap 6: Voer tests uit
      - name: Run tests
        run: |
          cd webapp
          yarn test

      # Stap 7: Lint de code
      - name: Lint de code
        env:
          ESLINT_USE_FLAT_CONFIG: false
        run: |
          cd webapp
          yarn lint

      # Stap 8: Log in op Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Stap 9: Build en push Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: webapp
          file: webapp/dockerfile
          tags: jonas12janssens/webapp:latest
          push: true

