---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Stap 1: Check de repository-code uit
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Ga naar de webapp directory
        run: cd dockerlab/webapp

      # Stap 2: Installeer NodeJS
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Stap 3: Installeer dependencies
      - name: Installeer dependencies
        run: yarn install

      # Stap 4: Lint de code
      - name: Lint de code
        run: yarn lint

      